spring.application.name=contratos

spring.datasource.url=jdbc:h2:mem:contratosdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# 2. Cria as tabelas sozinho usando as nossas classes (models)
spring.jpa.hibernate.ddl-auto=update

# 3. Mostra os comandos de banco de dados no painel inferior (ajuda a entender o que está acontecendo)
spring.jpa.show-sql=true

# 4. Cria uma tela na internet para a gente ver as tabelas e os dados salvos
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console